#!/usr/bin/python -O

from __future__ import print_function


from AmbariServer import AmbariServer
from HadoopShell import HadoopCmd, Seperator, HadoopShell


class AmbariShell(HadoopShell):
    rootpath = "/api/v1"
    commands = HadoopShell.commands + [
        HadoopCmd("list", "List all clusters"),
        HadoopCmd("list hosts", "List hosts", "[clusters]"),
        HadoopCmd("list host_components", "List hosts together with components",
                 ["<cluster>", "[host]"]),
        HadoopCmd("list services", "List services together with components",
                  ["<cluster>", "[service]"]),
        HadoopCmd("list alerts", "List all alerts", "<cluster>"),
        Seperator(),
        HadoopCmd("show", "Show a cluster", "<cluster>"),
        HadoopCmd("show component", "Show a component",
                  ["<cluster>", "<service>", "<component>"]),
        Seperator(),
        HadoopCmd("add service", "Add a service", ["<cluster>", "<service>"]),
        HadoopCmd("add component", "Add a component",
                  ["<cluster>", "<service>", "<component>"]),
        HadoopCmd("add host_component", "Add a component on a host",
                  ["<cluster>", "<host>", "<component>"]),
        HadoopCmd("install service", "Install a service",
                  ["<cluster>", "<service"]),
        HadoopCmd("install component", "Install a component",
                  ["<cluster>", "<host>", "<component>"]),
        Seperator(),
        HadoopCmd("start service", "Start a service",
                  ["<cluster>", "<service>"]),
        HadoopCmd("stop service", "Stop a service", ["<cluster>", "<service>"]),
        HadoopCmd("delete service", "Delete a service",
                  ["<cluster>", "<service>"]),
        HadoopCmd("start component", "Start a component",
                  ["<cluster>", "<service>", "<component>"]),
        HadoopCmd("stop component", "Stop a component",
                  ["<cluster>", "<service>", "<component>"]),
    ]

    def __init__(self):
        super(AmbariShell, self).__init__()

    @property
    def banner(self):
        return "Ambari Shell"


# command handlers
    def do_list(self, data):
        self.do_echo(self.server.do_list(data))

    def do_show(self, data):
        self.do_echo(self.server.do_show(data))

    def do_add(self, data):
        self.do_echo(self.server.do_add(data))

    def do_install(self, data):
        self.do_echo(self.server.do_install(data))

    def do_start(self, data):
        self.do_echo(self.server.do_start(data))

    def do_stop(self, data):
        self.do_echo(self.server.do_stop(data))

    def do_delete(self, data):
        self.do_echo(self.server.do_delete(data))

    def get_parser(self):
        parser = super(AmbariShell, self).get_parser()
        parser.add_option("--password", default="admin")
        parser.set_defaults(user="admin")

        return parser

# ---- main ----
if __name__ == '__main__':
    shell = AmbariShell()
    shell.start(AmbariServer)

