#!/usr/bin/python

from Ambari import Ambari

if __name__ == "__main__":
    from optparse import OptionParser

    parser = OptionParser()
    parser.add_option("--host", default="localhost")
    parser.add_option("-u", "--user", default="admin")
    parser.add_option("-p", "--password", default="admin")

    opts, args = parser.parse_args()

    if __debug__: print opts, args

    ambari = Ambari(opts.host, opts.user, opts.password)

    ambari.cmdloop()
