#!/usr/bin/python

from HadoopUtil import HadoopUtil

if __name__ == "__main__":
    from optparse import OptionParser

    parser = OptionParser()
    parser.add_option("--host", default="localhost")
    parser.add_option("--port", type=int, default=8080)
    parser.add_option("-u", "--user", default="noname")

    opts, args = parser.parse_args()

    if __debug__: print opts, args

    hadoop = HadoopUtil("http", opts.host, opts.port, opts.user)

    hadoop.cmdloop()
